#!/bin/bash

if [ $# -eq 1 ]
then
CARDS=$(cat /proc/asound/cards |  grep '\[*\]'  | cut -f 2 -d'[' | cut -f 1 -d']')
echo "***** SOUND CARD SELECTION *****"
cat /proc/asound/cards | cut -f 3- -d' '
select card in $CARDS;do
 if [[ -n $card ]]; then
        CARD="hw:"$card
	break
    else
        print 'invalid.'
    fi
done

echo "***** VIDEO CARD SELECTION *****"
displays=$(xrandr | grep connected | grep -v disconnected | cut -f 1 -d' ')
xrandr | grep connected| grep -v disconnected| cut -f 1 -d'('
select r in $displays;do
 if [[ -n $r ]]; then
        resolution=$(xrandr | grep $r |cut -f 1 -d'+' | awk '{print $NF}')
        xoff=$(xrandr | grep $r |cut -f 2 -d'+')
	yoff=$(xrandr | grep $r |cut -f 3 -d'+' | cut -f 1 -d' ')
	res=$resolution
        break
    else
        print 'invalid.'
    fi
done

OUT=$1
    for i in 5 4 3 2 1; do echo $i; sleep 1; done;echo "Press [q] to quit";
    ffmpeg  -loglevel panic -f x11grab -s $res -i :0.0+$xoff+$yoff -f alsa -ac 1 -i $CARD  -pix_fmt yuv420p $OUT
else
    echo "Incorrect Syntax"
    echo "record.sh filename"
fi

