#!/bin/bash

res=$(xrandr | grep \* | cut -d' ' -f 4)

if [ $# -eq 1 ]
then
OUT=$1
    for i in 5 4 3 2 1; do echo $i; sleep 1; done;echo "Press [q] to quit";
    ffmpeg  -f x11grab -s $res -i :0.0 -f alsa -ac 1 -i hw:Device  -strict experimental $OUT
    %ffmpeg -loglevel panic -f x11grab -s $res -i :0.0 -f alsa -ac 1 -i hw:Device -r 60 $OUT
else
    echo "Incorrect Syntax"
    echo "record.sh filename"
fi

